using System.Collections.Generic;

namespace PalServerLauncher.Config;

/// <summary>UI grouping for a PalWorldSettings.ini key (mirrors the official config doc's sections).</summary>
public enum SettingCategory
{
    ServerAdmin,
    Performance,
    Gameplay,
    GameBalance,
}

public enum SettingType
{
    Bool,
    Int,
    Float,
    Text,
    Enum,
    IpAddress,
    /// <summary>A value written back verbatim (no quoting) - for tuple/list values like
    /// <c>CrossplayPlatforms=(Steam,Xbox,PS5,Mac)</c> that the other types would mis-quote. The save path
    /// round-trip-verifies a Raw edit and refuses if it would corrupt the blob.</summary>
    Raw,
}

/// <summary>
/// Metadata for one PalWorldSettings.ini <c>OptionSettings</c> key: how to label it, which category
/// it belongs to, and how to type its value (which drives quoting on write via <see cref="OptionSettingsBlob"/>).
/// </summary>
public sealed record GameSetting(
    string Key,
    string Label,
    SettingCategory Category,
    SettingType Type,
    string Description = "",
    IReadOnlyList<string>? Options = null,
    double? Min = null,
    double? Max = null,
    bool Secret = false);

/// <summary>
/// Data-driven catalog of PalWorldSettings.ini <c>OptionSettings</c> keys as typed fields. Covers EVERY
/// key a current default config contains (verified against a real DefaultPalWorldSettings.ini), so the
/// "New Settings" panel - which lists keys the catalog doesn't know - is empty on a normal install and
/// only lights up when a future game update adds a key we haven't catalogued yet.
///
/// Types match the exact format the game writes (rates as 6-decimal floats, enums bare, strings quoted,
/// tuples/lists <see cref="SettingType.Raw"/>). Descriptions come from the official configuration
/// reference (docs/docs-palworldgame-com-settings-and-operation-configuration.md) with obvious English
/// mistakes fixed and the (deliberately vague) meaning left intact; the ~24 keys the doc omits carry a
/// short launcher-authored description instead. Each row's Description drives the field tooltip, rendered
/// as "Key&lt;newline&gt;Description".
/// </summary>
public static class GameSettingsCatalog
{
    public static readonly IReadOnlyList<GameSetting> All = new List<GameSetting>
    {
        // ===================== Server management (Admin Settings) =====================
        new("ServerName", "Server name", SettingCategory.ServerAdmin, SettingType.Text,
            "Server name."),
        new("ServerDescription", "Description", SettingCategory.ServerAdmin, SettingType.Text,
            "Server description."),
        new("ServerPassword", "Server password", SettingCategory.ServerAdmin, SettingType.Text,
            "Password required to log in to the server. Blank = no password.", Secret: true),
        new("AdminPassword", "Admin password", SettingCategory.ServerAdmin, SettingType.Text,
            "Password used to obtain administrative privileges on the server. Required for the REST API and RCON.", Secret: true),
        new("ServerPlayerMaxNum", "Max players", SettingCategory.ServerAdmin, SettingType.Int,
            "Maximum number of players who can join the server. The -players launch argument overrides this if set.", Min: 1),
        new("CoopPlayerMaxNum", "Co-op max players", SettingCategory.ServerAdmin, SettingType.Int,
            "Undocumented, but community says maximum cooperative-play party size.", Min: 1),
        new("RESTAPIEnabled", "REST API enabled", SettingCategory.ServerAdmin, SettingType.Bool,
            "Enable the REST API. The launcher needs this for stats, graceful shutdown, and player logging."),
        new("RESTAPIPort", "REST API port", SettingCategory.ServerAdmin, SettingType.Int,
            "Listening port for the REST API.", Min: 1, Max: 65535),
        new("RCONEnabled", "RCON enabled", SettingCategory.ServerAdmin, SettingType.Bool,
            "Enable RCON."),
        new("RCONPort", "RCON port", SettingCategory.ServerAdmin, SettingType.Int,
            "Port number used for RCON.", Min: 1, Max: 65535),
        new("bUseAuth", "Require authentication", SettingCategory.ServerAdmin, SettingType.Bool,
            "Undocumented. Defaults to True."),
        new("BanListURL", "Ban list URL", SettingCategory.ServerAdmin, SettingType.Text,
            "Undocumented, but likely the ban list the server checks against."),
        new("bIsUseBackupSaveData", "Built-in save backups", SettingCategory.ServerAdmin, SettingType.Bool,
            "Enable Palworld's own world backups (separate from the launcher's). Enabling this increases disk load."),
        new("AutoSaveSpan", "Auto-save interval (seconds)", SettingCategory.ServerAdmin, SettingType.Float,
            "How often the world auto-saves (seconds).", Min: 0),
        new("bIsShowJoinLeftMessage", "Show join/leave messages", SettingCategory.ServerAdmin, SettingType.Bool,
            "On dedicated servers, show in-game messages when players join or leave."),
        new("bAllowClientMod", "Allow client mods", SettingCategory.ServerAdmin, SettingType.Bool,
            "Allow players with mods enabled to join the server."),
        new("ChatPostLimitPerMinute", "Chat rate limit", SettingCategory.ServerAdmin, SettingType.Int,
            "Maximum number of chat messages allowed per minute.", Min: 0),
        new("LogFormatType", "Log format", SettingCategory.ServerAdmin, SettingType.Enum,
            "Server log file format.", new[] { "Text", "Json" }),
        new("bIsMultiplay", "Multiplayer session", SettingCategory.ServerAdmin, SettingType.Bool,
            "Undocumented. Set to False by default."),
        new("Region", "Region", SettingCategory.ServerAdmin, SettingType.Text,
            "Undocumented. Likely EU/NA or other region codes, but blank by default."),
        new("CrossplayPlatforms", "Crossplay platforms", SettingCategory.ServerAdmin, SettingType.Raw,
            "Allowed platforms to connect to the server, as a tuple. Default: (Steam,Xbox,PS5,Mac)."),
        new("PublicIP", "Public IP", SettingCategory.ServerAdmin, SettingType.IpAddress,
            "Community server: explicitly specify the external public IP. Blank = auto-detect."),
        new("PublicPort", "Public port", SettingCategory.ServerAdmin, SettingType.Int,
            "Community server: explicitly specify the external public port. Does not change the server's listening port.", Min: 1, Max: 65535),

        // ===================== Performance =====================
        new("BaseCampMaxNum", "Max bases (world)", SettingCategory.Performance, SettingType.Int,
            "Maximum total number of base camps on the map (all guild bases combined).", Min: 0),
        new("BaseCampMaxNumInGuild", "Max bases per guild", SettingCategory.Performance, SettingType.Int,
            "Maximum number of bases per guild. Default 4 (max 10). Increasing this raises processing load.", Min: 0, Max: 10),
        new("BaseCampWorkerMaxNum", "Max Pals per base", SettingCategory.Performance, SettingType.Int,
            "Maximum number of Pals per base (max 50). Increasing this raises processing load.", Min: 0, Max: 50),
        new("MaxBuildingLimitNum", "Building limit per player", SettingCategory.Performance, SettingType.Int,
            "Per-player building count cap (0 = unlimited).", Min: 0),
        new("DropItemMaxNum", "Max dropped items", SettingCategory.Performance, SettingType.Int,
            "Maximum number of items lying dropped in the world before they start to despawn.", Min: 0),
        new("DropItemMaxNum_UNKO", "Max dropped droppings", SettingCategory.Performance, SettingType.Int,
            "Undocumented. Likely the max number of droppings (UNKO) in the world; appears to be unused in game.", Min: 0),
        new("ServerReplicatePawnCullDistance", "Pal sync distance", SettingCategory.Performance, SettingType.Float,
            "Pal sync distance from players (cm). Minimum 5000, maximum 15000.", Min: 5000, Max: 15000),
        new("ItemContainerForceMarkDirtyInterval", "Container re-sync interval", SettingCategory.Performance, SettingType.Float,
            "How often to force a re-sync while a container UI is open (seconds).", Min: 0),

        // ===================== Features (Gameplay) =====================
        new("Difficulty", "Difficulty", SettingCategory.Gameplay, SettingType.Enum,
            "Difficulty preset. None applies your individual settings below.", new[] { "None", "Casual", "Normal", "Hard" }),
        new("bHardcore", "Hardcore", SettingCategory.Gameplay, SettingType.Bool,
            "Enable Hardcore. You will not be able to respawn on death."),
        new("bCharacterRecreateInHardcore", "Recreate character (Hardcore)", SettingCategory.Gameplay, SettingType.Bool,
            "Whether you may recreate your character upon death in Hardcore mode."),
        new("bIsPvP", "PvP", SettingCategory.Gameplay, SettingType.Bool,
            "Enable PvP. Only takes effect with Player-vs-player damage and Base defense vs. other guilds also on."),
        new("bEnablePlayerToPlayerDamage", "Player-vs-player damage", SettingCategory.Gameplay, SettingType.Bool,
            "Let players harm each other. One of the three settings that together enable PvP."),
        new("bEnableFriendlyFire", "Friendly fire", SettingCategory.Gameplay, SettingType.Bool,
            "Undocumented. Community says it lets players and their Pals damage members of their own guild."),
        new("bCanPickupOtherGuildDeathPenaltyDrop", "Loot other guilds' drops", SettingCategory.Gameplay, SettingType.Bool,
            "Allow players to pick up the Pals and items dropped by other guilds' players on death."),
        new("bEnableDefenseOtherGuildPlayer", "Base defense vs. other guilds", SettingCategory.Gameplay, SettingType.Bool,
            "Base Pals engage hostile players who trespass into your base. One of the three settings that enable PvP."),
        new("bEnableFastTravel", "Fast travel", SettingCategory.Gameplay, SettingType.Bool,
            "Enable fast travel."),
        new("bEnableFastTravelOnlyBaseCamp", "Fast travel only between bases", SettingCategory.Gameplay, SettingType.Bool,
            "Restrict fast travel to between bases only."),
        new("bEnableInvaderEnemy", "Invaders", SettingCategory.Gameplay, SettingType.Bool,
            "Enable Invaders."),
        new("EnablePredatorBossPal", "Predator Pals", SettingCategory.Gameplay, SettingType.Bool,
            "Allows Predator Pals to spawn in the world."),
        new("bBuildAreaLimit", "Build area limit", SettingCategory.Gameplay, SettingType.Bool,
            "Prevent building near structures such as fast-travel points."),
        new("bInvisibleOtherGuildBaseCampAreaFX", "Show base area boundaries", SettingCategory.Gameplay, SettingType.Bool,
            "Show base area boundaries."),
        new("bShowPlayerList", "Player list in ESC menu", SettingCategory.Gameplay, SettingType.Bool,
            "Enable the player list on the ESC menu."),
        new("bExistPlayerAfterLogout", "Body stays after logout", SettingCategory.Gameplay, SettingType.Bool,
            "Whether players enter a sleeping state at their current location when logging out."),
        new("bEnableNonLoginPenalty", "Offline penalty", SettingCategory.Gameplay, SettingType.Bool,
            "Undocumented. May relate to whether your Pals get debuffs when you haven't logged in. Untested."),
        new("bIsStartLocationSelectByMap", "Choose starting location", SettingCategory.Gameplay, SettingType.Bool,
            "Whether to allow players to choose their starting location."),
        new("bActiveUNKO", "Droppings (UNKO)", SettingCategory.Gameplay, SettingType.Bool,
            "Undocumented. May be related to ranch Pal drops (dung), but untested/unknown."),
        new("bEnableAimAssistPad", "Aim assist (controller)", SettingCategory.Gameplay, SettingType.Bool,
            "Aim assist for controllers. Set to False to disable it."),
        new("bEnableAimAssistKeyboard", "Aim assist (keyboard)", SettingCategory.Gameplay, SettingType.Bool,
            "Enable aim assist for mouse & keyboard."),
        new("bAllowEnhanceStat_Attack", "Allow stat points: Attack", SettingCategory.Gameplay, SettingType.Bool,
            "Allow allocating stat points to Attack."),
        new("bAllowEnhanceStat_Health", "Allow stat points: HP", SettingCategory.Gameplay, SettingType.Bool,
            "Allow allocating stat points to HP."),
        new("bAllowEnhanceStat_Stamina", "Allow stat points: Stamina", SettingCategory.Gameplay, SettingType.Bool,
            "Allow allocating stat points to Stamina."),
        new("bAllowEnhanceStat_Weight", "Allow stat points: Carry Weight", SettingCategory.Gameplay, SettingType.Bool,
            "Allow allocating stat points to Carry Weight."),
        new("bAllowEnhanceStat_WorkSpeed", "Allow stat points: Work Speed", SettingCategory.Gameplay, SettingType.Bool,
            "Allow allocating stat points to Work Speed."),
        new("bAllowGlobalPalboxExport", "Global Palbox export", SettingCategory.Gameplay, SettingType.Bool,
            "Allow saving to the Global Palbox."),
        new("bAllowGlobalPalboxImport", "Global Palbox import", SettingCategory.Gameplay, SettingType.Bool,
            "Allow loading from the Global Palbox."),
        new("bAutoResetGuildNoOnlinePlayers", "Auto-reset inactive guilds", SettingCategory.Gameplay, SettingType.Bool,
            "If no guild members log in, automatically delete structures and base Pals."),
        new("AutoResetGuildTimeNoOnlinePlayers", "Auto-reset guild after (hours)", SettingCategory.Gameplay, SettingType.Float,
            "Offline duration before an inactive guild is auto-reset (hours). Ignored unless 'Auto-reset inactive guilds' is on.", Min: 0),
        new("bDisplayPvPItemNumOnWorldMap_BaseCamp", "Show base PvP items on map", SettingCategory.Gameplay, SettingType.Bool,
            "Whether to show, on the map, the number of PvP-exclusive items in each base."),
        new("bDisplayPvPItemNumOnWorldMap_Player", "Show player PvP items on map", SettingCategory.Gameplay, SettingType.Bool,
            "Whether to show player locations and the number of PvP-exclusive items on the map."),
        new("bIsRandomizerPalLevelRandom", "Randomize Pal levels", SettingCategory.Gameplay, SettingType.Bool,
            "If on, wild Pal levels are fully random. If off, levels are randomized within each area's intended range."),
        new("RandomizerType", "Pal randomizer mode", SettingCategory.Gameplay, SettingType.Enum,
            "Pal spawn randomization mode. None = no randomization; Region = randomize per region; All = fully randomized.", new[] { "None", "Region", "All" }),
        new("RandomizerSeed", "Randomizer seed", SettingCategory.Gameplay, SettingType.Text,
            "Seed value used when Pal spawn randomization is enabled."),

        // ===================== Game balances =====================
        new("DayTimeSpeedRate", "Day speed", SettingCategory.GameBalance, SettingType.Float,
            "Daytime progression speed.", Min: 0),
        new("NightTimeSpeedRate", "Night speed", SettingCategory.GameBalance, SettingType.Float,
            "Nighttime progression speed.", Min: 0),
        new("ExpRate", "EXP rate", SettingCategory.GameBalance, SettingType.Float,
            "EXP gain multiplier.", Min: 0),
        new("PalCaptureRate", "Capture rate", SettingCategory.GameBalance, SettingType.Float,
            "Capture rate multiplier.", Min: 0),
        new("PalSpawnNumRate", "Pal spawn rate", SettingCategory.GameBalance, SettingType.Float,
            "Pal spawn rate. Impacts performance.", Min: 0),
        new("PalEggDefaultHatchingTime", "Huge Egg hatch time (hours)", SettingCategory.GameBalance, SettingType.Float,
            "Time to hatch a Huge Egg (hours). Other eggs also require time to incubate.", Min: 0),
        new("WorkSpeedRate", "Work speed", SettingCategory.GameBalance, SettingType.Float,
            "How fast both players and Pals complete work. Multiplier: 2.0 = work completed twice as fast.", Min: 0),
        new("PalDamageRateAttack", "Pal damage dealt", SettingCategory.GameBalance, SettingType.Float,
            "Damage dealt by Pals multiplier.", Min: 0),
        new("PalDamageRateDefense", "Pal damage taken", SettingCategory.GameBalance, SettingType.Float,
            "Damage taken by Pals multiplier.", Min: 0),
        new("PlayerDamageRateAttack", "Player damage dealt", SettingCategory.GameBalance, SettingType.Float,
            "Damage dealt by players multiplier.", Min: 0),
        new("PlayerDamageRateDefense", "Player damage taken", SettingCategory.GameBalance, SettingType.Float,
            "Damage taken by players multiplier.", Min: 0),
        new("PlayerStomachDecreaceRate", "Player hunger rate", SettingCategory.GameBalance, SettingType.Float,
            "Player hunger depletion rate multiplier.", Min: 0),
        new("PlayerStaminaDecreaceRate", "Player stamina rate", SettingCategory.GameBalance, SettingType.Float,
            "Player stamina depletion rate multiplier.", Min: 0),
        new("PlayerAutoHPRegeneRate", "Player HP regen", SettingCategory.GameBalance, SettingType.Float,
            "Player natural HP regen multiplier.", Min: 0),
        new("PlayerAutoHpRegeneRateInSleep", "Player HP regen (sleep)", SettingCategory.GameBalance, SettingType.Float,
            "Player HP regen while sleeping multiplier.", Min: 0),
        new("PalStomachDecreaceRate", "Pal hunger rate", SettingCategory.GameBalance, SettingType.Float,
            "Pal hunger depletion rate multiplier.", Min: 0),
        new("PalStaminaDecreaceRate", "Pal stamina rate", SettingCategory.GameBalance, SettingType.Float,
            "Pal stamina depletion rate multiplier.", Min: 0),
        new("PalAutoHPRegeneRate", "Pal HP regen", SettingCategory.GameBalance, SettingType.Float,
            "Pal natural HP regen multiplier.", Min: 0),
        new("PalAutoHpRegeneRateInSleep", "Pal HP regen (Palbox)", SettingCategory.GameBalance, SettingType.Float,
            "Pal HP regen while sleeping in the Palbox multiplier.", Min: 0),
        new("CollectionDropRate", "Gather drop rate", SettingCategory.GameBalance, SettingType.Float,
            "Gatherable items multiplier.", Min: 0),
        new("CollectionObjectHpRate", "Gatherable HP", SettingCategory.GameBalance, SettingType.Float,
            "Gatherable objects health multiplier.", Min: 0),
        new("CollectionObjectRespawnSpeedRate", "Gatherable respawn", SettingCategory.GameBalance, SettingType.Float,
            "Gatherable objects respawn interval multiplier.", Min: 0),
        new("EnemyDropItemRate", "Enemy drop rate", SettingCategory.GameBalance, SettingType.Float,
            "Dropped item quantity multiplier.", Min: 0),
        new("DropItemAliveMaxHours", "Dropped item lifetime (hours)", SettingCategory.GameBalance, SettingType.Float,
            "How long dropped items remain in the world before they despawn (hours). Lowering it helps server cleanup / performance.", Min: 0),
        new("ItemWeightRate", "Item weight", SettingCategory.GameBalance, SettingType.Float,
            "Item weight multiplier.", Min: 0),
        new("ItemCorruptionMultiplier", "Item corruption speed", SettingCategory.GameBalance, SettingType.Float,
            "Item corruption speed multiplier.", Min: 0),
        new("EquipmentDurabilityDamageRate", "Equipment durability loss", SettingCategory.GameBalance, SettingType.Float,
            "Equipment durability loss multiplier.", Min: 0),
        new("BuildObjectHpRate", "Building HP", SettingCategory.GameBalance, SettingType.Float,
            "Multiplier for how much health buildings have. 2.0 = double building HP.", Min: 0),
        new("BuildObjectDamageRate", "Building damage", SettingCategory.GameBalance, SettingType.Float,
            "Damage multiplier to buildings.", Min: 0),
        new("BuildObjectDeteriorationDamageRate", "Building decay speed", SettingCategory.GameBalance, SettingType.Float,
            "Building decay speed multiplier.", Min: 0),
        new("DeathPenalty", "Death penalty", SettingCategory.GameBalance, SettingType.Enum,
            "Death penalty. None = no drops; Item = drop all items except equipment; ItemAndEquipment = drop all items; All = drop all items and all Pals on your team.",
            new[] { "None", "Item", "ItemAndEquipment", "All" }),
        new("bPalLost", "Lose Pals on death", SettingCategory.GameBalance, SettingType.Bool,
            "Permanently lose Pals on death."),
        new("BlockRespawnTime", "Respawn cooldown (seconds)", SettingCategory.GameBalance, SettingType.Float,
            "Cooldown before you can respawn after death (seconds).", Min: 0),
        new("RespawnPenaltyDurationThreshold", "Respawn penalty threshold", SettingCategory.GameBalance, SettingType.Float,
            "Survival-time threshold (seconds). Dying again before surviving this long applies the respawn cooldown multiplier below.", Min: 0),
        new("RespawnPenaltyTimeScale", "Respawn penalty multiplier", SettingCategory.GameBalance, SettingType.Float,
            "Multiplier applied to the respawn cooldown.", Min: 0),
        new("GuildPlayerMaxNum", "Max players per guild", SettingCategory.GameBalance, SettingType.Int,
            "Maximum number of players per guild.", Min: 0),
        new("GuildRejoinCooldownMinutes", "Guild rejoin cooldown (min)", SettingCategory.GameBalance, SettingType.Int,
            "Cooldown before rejoining a guild (minutes).", Min: 0),
        new("DenyTechnologyList", "Disabled technologies", SettingCategory.GameBalance, SettingType.Raw,
            "Disable specific technologies. Specify Technology IDs - example: (\"PALBOX\", \"RepairBench\"). Blank = none."),
        new("bAdditionalDropItemWhenPlayerKillingInPvPMode", "PvP kill: drop item", SettingCategory.GameBalance, SettingType.Bool,
            "Whether to drop a special item when a player is killed while PvP is enabled."),
        new("AdditionalDropItemWhenPlayerKillingInPvPMode", "PvP kill: item ID", SettingCategory.GameBalance, SettingType.Text,
            "The ID of the item to drop on a PvP kill (used when 'PvP kill: drop item' is on)."),
        new("AdditionalDropItemNumWhenPlayerKillingInPvPMode", "PvP kill: item count", SettingCategory.GameBalance, SettingType.Int,
            "The quantity of the item to drop on a PvP kill (used when 'PvP kill: drop item' is on).", Min: 0),
        new("SupplyDropSpan", "Supply drop interval (min)", SettingCategory.GameBalance, SettingType.Int,
            "Meteorite / supply drop interval (minutes).", Min: 0),
    };
}
